name: Download
on:
  workflow_dispatch:
  push:
    branches:
      - master

  schedule:
    - cron: "0 */3 * * *"
      

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0 # need to check if this is necessary, may be grabbing unnecessary commit data

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download PV4EV
        run: |
          python3 webscraper.py
        env:
          username: ${{ secrets.LOGIN_USERNAME }}
          password: ${{ secrets.LOGIN_PASSWORD }}

      - name: Download CO2
        run: |
          python3 co2webscraper.py
        env:
          username: ${{ secrets.LOGIN_USERNAME }}
          password: ${{ secrets.LOGIN_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with: 
          name: selenium-logs
          path: selenium-logs.txt

      - uses: actions/upload-artifact@v2
        with: 
          name: selenium-logs-co2
          path: selenium-logs-co2.txt

      - name: Commit Data
        run: | # add timestamp system here
          git config --global user.name 'Github Action'
          git config --global user.email '<>'

          rm -rf .github/
          rm .gitignore
          rm README.md
          rm requirements.txt
          rm webscraper.py
          rm selenium-logs.txt
          rm selenium-logs-co2.txt
          rm co2webscraper.py
      
          git add .
          git commit -m 'Retrieving new data'

          git push origin master:data --force
      

