name: Download
on:
  workflow_dispatch:
  push:
    branches:
      - master
      

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0 # need to check if this is necessary, may be grabbing unnecessary commit data

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download
        run: |
          python3 webscraper.py
        env:
          username: ${{ secrets.LOGIN_USERNAME }}
          password: ${{ secrets.LOGIN_PASSWORD }}

      - name: Commit Data
        run: | # add timestamp system here
          git add *.csv
          git commit -m 'Retrieving new data'
      
      - name: Push Data
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'data'

