name: Download
on:
  push:
    branches:
      - master
      
  schedule:
    - cron: "*/3 * * * *"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0 # need to check if this is necessary, may be grabbing unnecessary commit data

      - name: Setup Python
        needs: Checkout
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Download
        needs: Setup Python
        run: |
          python3 webscraper.py
        env:
          username: ${{ secrets.LOGIN_USERNAME }}
          password: ${{ secrets.LOGIN_PASSWORD }}

      - name: Commit Data
        needs: Download
        run: | # add timestamp system here
          git add *.csv
          git commit -m 'Retrieving new data'
      
      - name: Push Data
        needs: Commit Data
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'data'

